blog/urls.py
from django.urls import include, path
from blog.views import *

app_name='blog'
urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<slug:slug>/', PostDV.as_view(), name='post_detail'),
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    # path('today/', PostTAV.as_view(), name='post_today_archive'),
]

bookmark/urls.py
from django.urls import include, path
from bookmark.views import BookmarkLV, BookmarkDV

app_name='bookmark'
urlpatterns = [
    # Class-based views
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:id>', BookmarkDV.as_view, name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls', namespace='bookmark')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('photo/',include('photo.urls', namespace='photo')),
]

photo/urls.py
from django.urls import include, path
from photo.views import *

app_name='photo'
urlpatterns=[
    path('',AlbumLV.as_view(), name='index'),
    path('album/',AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>', AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>', PhotoDV.as_view(), name='photo_detail'),
]

blog/models.py
from __future__ import unicode_literals # Python 2.x 지원용
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.urls import reverse

# Create your models here.

@python_2_unicode_compatible # Python 2.x 지원용
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))
    
    def get_previous_post(self):
        return self.get_previous_by_modify_date()
    
    def get_next_post(self):
        return self.get_next_by_modify_date()

bookmark/models.py
from __future__ import unicode_literals # Python 2.x 지원용

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible # Python 2.x 지원용
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)

    def __str__(self):
        return self.title

photo/models.py
from __future__ import unicode_literals  # Python 2.x 지원용
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.urls import reverse

from photo.fields import ThumbnailImageField


@python_2_unicode_compatible  # Python 2.x 지원용
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(
        'One Line Description', max_length=100, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))


@python_2_unicode_compatible  # Python 2.x 지원용
class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from blog.models import Post

# Create your views here.

#--- ListView
class PostLV(ListView) :
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

#--- DetailView
class PostDV(DetailView):
    model = Post

#--- ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'

bookmark/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

mysite/views.py
from django.views.generic.base import TemplateView

# Create your views here

#--- TemplateView
class HomeView(TemplateView):
    template_name = 'home.html'

photo/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from photo.models import Album, Photo

# Create your views here.

class AlbumLV(ListView):
    model = Album
class AlbumDV(DetailView):
    model = Album
class PhotoDV(DetailView):
    model = Photo

blog/templates/blog/post_all.html
{% extends "base.html" %}

{%block title %}Django Bookmark List{% endblock %}

{% block content %}
<div id="content">

    <h1>Blog List</h1>

    {% for post in posts %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.description }}</p>
    {% endfor %}

    <br />

    <div>
        <span>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_archive.html
{% extends "base.html" %}

{%block title %}Django Bookmark List{% endblock %}

{% block content %}
<div id="content">
<h1>Post Archives until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a></li>
    {% endfor %}
</ul>

<br/>

<div>
    <ul>
        {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
    </ul>
</div>
</div>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{%block title %}Django Bookmark List{% endblock %}

{% block content %}
<div id="content">

    <h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{%block title %}Django Bookmark List{% endblock %}

{% block content %}
<div id="content">
    <h1>Post Archives for {{ month|date:"N, Y" }}</h1>

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{%block title %}Django Bookmark List{% endblock %}

{% block content %}
<div id="content">
    <h1>Post Archives for {{ year|date:"Y" }}</h1>

    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a></li>
        {% endfor %}
    </ul>

    <br />

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{%block title %}Django Bookmark List{% endblock %}

{% block content %}
<div id="content">
    <h2>{{ object.title }}</h2>

    <p class="other_posts">
        {% if object.get_previous_by_modify_date %}
        <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post">
            &laquo;--{{ object.get_previous_post }}</a>
        {% endif %}

        {% if object.get_next_by_modify_date %}
        | <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">
            {{ object.get_next_post }}--&raquo;</a>
        {% endif %}
    </p>

    <p class="date">{{ object.modify_date|date:"j F Y" }}</p>
    <br />

    <div class="body">
        {{ object.content|linebreaks }}
    </div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}Django Bookmark Detail{% endblock %}

{% block content %}
<div id="content">
    <h1>{{ object.title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{%block title %}Django Bookmark List{% endblock %}

{% block content %}
<div id="content">
    <h1>Bookmark List</h1>

    <ul>
        {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

photo/templates/photo/album_detail.html
{% extends "base.html" %}

{%block title %}album_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h2 style="display:inline">{{ object.name }}</h2>
    &emsp;<b><i>{{ object.description }}</i></b>

    <hr/>

    <div class="album-detail">
        {% for photo in object.photo_set.all %}
            <div class="album-detail-photo">
                <a href="{{ photo.get_absolute_url }}">
                    <img class="thumbnail" src="{{ photo.image.thumb_url }}" alt="">
                </a>
                <li>{{ photo.title }}</li>
                <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
            </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

photo/templates/photo/album_list.html
{% extends "base.html" %}

{%block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">
    {% for item in object_list %}
        <div class="clear_float">
            <h2 style="display:inline">
                <a href="{% url 'photo:album_detail' item.id %}">
                    {{ item.name }}
                </a>
            </h2>
            &emsp;<b><i>{{ item.description }}</i></b>
        </div>

        <hr/>

        <div class="album-list">
            {% for photo in item.photo_set.all|slice:":5" %}
                <div class="album-list-photo">
                    <a href="{{ photo.get_absolute_url }}">
                        <img class="thumbnail" src="{{ photo.image.thumb_url }}" alt="">
                    </a>
                </div>
            {% endfor %}
        </div>
    {% endfor %}

</div>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{%block title %}photo_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h2>{{ object.title }}</h2>

    <table class="photo-detail">
        <tr>
            <td>
                <a href="{{ object.image.url }}">
                    <img style="max-width:100%" src="{{ object.image.url }}" alt="">
                </a>
            </td>

            <td>
                <ul>
                    <li>Photo Description</li>
                    {% if object.description %}<p>{{ object.description|linebreaks }}</p>
                    {% else %}<p>(black)</p>
                    <li>Date Uploaded</li>
                    <p>{{ object.upload_date }}</p>
                    <li>Album Name</li>
                    <p><a href="{% url 'photo:album_detail' object.album.id">
                        {{ object.album.name }}
                    </a></p>
                </ul>
            </td>
        </tr>
    </table>

</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>{% block title %}Django Web Programming{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href='{% static "css/base.css" %}'>
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}">
</head>

<body>
    <div id="header">
        <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
        <h4 class="welcome">Welcome, <a href="#">user name</a>/
            <a href="#">Change Password</a>/
            <a href="#">Logout</a></h4>
    </div>

    <div id="menu">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
        <li><a href="{% url 'blog:index' %}">Blog</a></li>
        <li><a href="#">Photo</a></li>

        <li><a href="#">Add&bigtriangledown;</a>
            <ul>
                <li><a href="#">Bookmark</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Photo</a></li>
            </ul>
        </li>

        <li><a href="#">Change&bigtriangledown;</a>
            <ul>
                <li><a href="#">Bookmark</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Photo</a></li>
            </ul>
        </li>

        <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
        <li><a href="#">Search</a></li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
    </div>

    {% block content %}{% endblock %}

    {% block footer %}{% endblock %}
</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}
<div id="content_home">
    <div id="homeimg">
        <a href="/"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"/></a>
        <h4 style="margin: 0;">This is Django powered web site.</h4>
    </div>

    <hr style="margin: 5px 0;">

    <h2>Select Application</h2>

    <table id="applist">
        <tr>
            <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="#">Add</a></i></td>
            <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>
        <tr>
            <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="#">Add</a></i></td>
            <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>
        <tr>
            <td><b><i><a href="#">Photo</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="#">Add</a></i></td>
            <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; user 2018
</div>
{% endblock footer %}